export const therapistLibraryFiles = [
	'100 Years Of Pt. Hillman.pdf',
	'8 Principles Of Hakomi.pdf',
	'Chief Seattles Letter.pdf',
	'Constancy Suzuki 2.pdf',
	'Constancy Suzuki.pdf',
	'Encouragement Of Zazen.pdf',
	'Enso.pdf',
	'Fixing And Healing.pdf',
	'Ghant Masochism Submission Surrender 2.pdf',
	'Ghent Surrender.pdf',
	'Healing Presence.pdf',
	'Heart Sutra Tanahashi.pdf',
	'How To Be.pdf',
	'Listening With The Body.pdf',
	'Love After Love.pdf',
	'Ma.pdf',
	'Maka Han Nya Hara Mita Shin Gyo.pdf',
	'Mindfulness Meditation To Teach Beginning Therapists Therapeutic Presence.pdf',
	'No Mud No Lotus.pdf',
	'No Self Barry Magid.pdf',
	'No Trace Suzuki Zmbm.pdf',
	'Non Interpretive Mechanisms In Psychoanalytic Therapy.pdf',
	'Only Dont Know.pdf',
	'Posture.pdf',
	'Psychology Of Awekaning Chapter11.pdf',
	'Psychology Of Awekaning Chapter12.pdf',
	'Psychology Of Awekaning Chapter16.pdf',
	'Psychology Of Awekaning Chapter17.pdf',
	'Pt As A Practice Of Love Welwood.pdf',
	'Radicalacceptance Chapter3 (1).pdf',
] as const;

export const therapistLibraryHref = (filename: string) =>
	`/_gated/therapist-library/${encodeURIComponent(filename)}`;
